[package]
name = "hdcd"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.15.3"

[dev-dependencies]
rstest = "0.11.0"
assert_approx_eq = "1.1.0"