[package]
name = "changeforest_py"
version = "1.1.4"
edition = "2021"
readme = "README.md"

[lib]
name = "changeforest"
crate-type = ["cdylib"]

[package.metadata.maturin]
name = "changeforest"

[dependencies]
numpy = "0.19"
changeforest = { path = "../" }
ndarray = "0.16"
pyo3 = {version = "0.19", features = ["extension-module"]}
biosphere = "0.4.0"
