[package]
name = "changeforest_py"
version = "1.1.3"
edition = "2021"

[lib]
name = "changeforest"
crate-type = ["cdylib"]

[package.metadata.maturin]
name = "changeforest"

[dependencies]
numpy = "0.19"
changeforest = { path = "../" }
ndarray = "0.15"
pyo3 = {version = "0.19", features = ["extension-module"]}
biosphere = "0.3.0"