[package]
name = 'changeforestr'
publish = false
version = '1.2.0'
edition = '2021'

[lib]
crate-type = [ 'staticlib' ]
name = 'changeforestr'

[dependencies]
extendr-api = { version="0.8", features = ["ndarray"] }
changeforest = { path = "../../../" }
ndarray = "0.16"
biosphere = "0.4.0"
