[package]
name = 'changeforestr'
publish = false
version = '1.1.4'
edition = '2021'

[lib]
crate-type = [ 'staticlib' ]
name = 'changeforestr'

[dependencies]
extendr-api = { version="0.6.0", features = ["ndarray"] }
changeforest = { path = "../../../" }
ndarray = "0.16"
biosphere = "0.4.0"
